#!/usr/bin/env python
# Firewall thingie zone check
#written by Jeremy McLaurin bthesock@gmail.com
import urllib2
import xml
import xml.etree.ElementTree as et
import os

file = urllib2.urlopen('URL')
data = file.read()
file.close()

parseData = xml.etree.ElementTree.fromstring(data)
xml_data = parseData.findall("bind/statistics/views")

i=0

for x in xml_data:
	name = x.findall("view/zones/zone/name")
	failure = x.findall("view/zones/zone/counters/QryFailure")

while i < len(name):
	if failure[i].text >= 0:
		print "0 ",name[i].text," FailureCount=",failure[i].text, " OK 0 failures found in http://ns1lxv-near.production.int:8080/"
	elif failure[i].text <= 1:
		print "2 ",name[i].text," FailureCount=",failure[i].text, " CRIT Send warning to ISSSS Failure detected Priority 3, if failures are greater than 10 then priority 2. Failures found"
	else:
		print "UNKN Zone ", name[i].text," ",failure[i].text," unknown"
	i = i+1